name: Thibault Cosnier
description: Materials Science Engineer. PhD Candidate @ <a style="color:#FFF;" href="http://www.leti-cea.com/cea-tech/leti/english" target="_blank">CEA LETI</a>.
meta_title: "Thibault Cosnier - Materials Science Engineer. PhD Candidate."
meta_description: "Hi there, my name is Thibault. I'm an engineer with key qualifications in semiconductor physics, devices and modeling. "

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 'http://tcosnier.github.io/'
domain_name: 'http://tcosnier.github.io'
google_analytics: 'UA-109498578-1'
gems: [jekyll-paginate, jekyll-seo-tag]

# Details for the RSS feed generator
url:            'http://tcosnier.github.io'
author:         'Thibault Cosnier'

twitter:
  username: ThibaultCosnier
  
social:
  name: Thibault Cosnier
  links:
    - https://twitter.com/ThibaultCosnier
    - https://www.facebook.com/thibault.cosnier
    - https://www.linkedin.com/in/ThibaultCosnier
    - https://plus.google.com/+ThibaultCosnier
    - https://github.com/tcosnier
    - https://keybase.io/tcosnier
