name: Thibault Cosnier
description: Materials Science Engineer. PhD Student.
meta_description: "Materials Science Engineer. PhD Student"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 'http://tcosnier.github.io'
domain_name: 'http://tcosnier.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://tcosnier.github.io'
author:         'Thibault Cosnier'
