name: Thibault Cosnier
description: Materials Science Engineer. PhD Candidate @ <a style="color:#FFF;" href="http://www.leti-cea.com/cea-tech/leti/english" target="_blank">CEA LETI</a>.
meta_description: "Materials Science Engineer. PhD Candidate @ CEA LETI"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 'http://tcosnier.github.io/'
domain_name: 'http://tcosnier.github.io'
google_analytics: 'UA-109498578-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://tcosnier.github.io'
author:         'Thibault Cosnier'
